# Server Configuration
server.port=8080
server.servlet.context-path=/

# Application Name
spring.application.name=job-application-api

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/job_applications_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.hikari.maximum-pool-size=30

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.com.example.jobapplication=DEBUG

# Jackson Configuration
spring.jackson.serialization.indent-output=true

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ Queue Topology
#  python -m locust -f "D:\My Learning\System Design\system-design\high-traffic-app\locustfile.py" --host=http://localhost:8080
# python -m py_compile "D:\My Learning\System Design\system-design\high-traffic-app\locustfile.py"
app.rabbitmq.queue=job.application.queue.v2
app.rabbitmq.exchange=job.application.exchange
app.rabbitmq.routing-key=job.application.created

# RabbitMQ Dead Letter Queue (DLQ) Configuration
app.rabbitmq.dlx=job.application.dlx
app.rabbitmq.dlq=job.application.dlq
app.rabbitmq.dlq-routing-key=job.application.dead

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=mypassword

# Rate Limiting Configuration
app.rate-limit.enabled=true
app.rate-limit.window-seconds=60
app.rate-limit.get-all-requests=100000
app.rate-limit.other-requests=100000
app.rate-limit.read-requests=120
app.rate-limit.write-requests=60

# Monitoring + Metrics
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

